ministryofjustice/hmpps-education-employment-api

helm_deploy/hmpps-education-employment-api/values.yaml

previous PR fixed secret referencing, but left the bad one in by mistake - now removed

ESWE-359 remove bad secret ref

---

.circleci/config.yml
helm_deploy/values-preprod.yaml

👷 Enable preprod and prod deployments
🔧 Reduce number of pods for preprod
Signed-off-by: theDustRoom <paul.massey@digital.justice.gov.uk>

ESWE-485 - Enable PreProd and Prod Deployments

---

.circleci/config.yml
helm_deploy/hmpps-education-employment-api/Chart.yaml
helm_deploy/values-preprod.yaml

Our orb and chart were outdated so I've upgraded them

ESWE-485 Enable Deployments

---

helm_deploy/hmpps-education-employment-api/Chart.yaml

Upgrade generic-service to latest

ESWE-752 - Upgrade Helm Charts

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/ReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARTestData.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/SARReadinessProfileDTO.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/SARTestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceControllerTest.kt

1) move data inside "content"
2) revise tests to verify SAR body's content

[ESWE-1079] Fix SAR endpoint; move data to content

---

.circleci/config.yml
README.md
build.gradle.kts
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/IntegrationTestBase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/testcontainers/PostgresContainer.kt
src/main/resources/application-localdb.yml
src/main/resources/application.yml

1) Spring `local` profile 
- Revise README.md
- Add spring profile group `local` for easier startup
3) Run integration test with temp DB in containers
- Run integration tests with postgres DB in temp containers
- use postgresql `16.2` image (was `14` on Circle CI)

[ESWE-1079] Refactor for local run and tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/service/ProfileService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/TestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/service/ProfileServiceTest.kt

1) add dates/period filter to ReadinessProfile and its history entries
2) add relevant unit tests
3) change TestData to object (from class with companion object); revise test data/objects

[ESWE-1079] implement dates (period) filter at ProfileService

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/ReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARTestData.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/util/TestData.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceControllerTest.kt
src/test/resources/CreateProfileDeclinedHistories.json

1) switch to new service call to filter by specified period (from date, to date)
2) add dates/period filtering cases to integration tests
3) convert TestData to object (was class with companion object)

[ESWE-1079] implement dates (period) filter at SARResourceController

---

helm_deploy/values-dev.yaml

set env var `HMPPS_SAR_ADDITIONALACCESSROLE` = `WORK_READINESS_VIEW` for testing SAR endpoint on dev env.

[ESWE-1079] additional role for testing SAR on dev

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/ReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileGetShould.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/SARReadinessProfileDTO.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/SARTestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/TestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceControllerTest.kt

1) fix the data type of notes (should be a list instead of single object)
2) revise test cases for missing coverage at notes

[ESWE-1079] fix de-serialisation issue at SAR notes

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileGetShould.kt

Rearrange SAR test cases with inner classes

[ESWE-1088] Rearrange SAR tests

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARTestData.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/config/CapturedSpringConfigValues.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/SARReadinessProfileDTO.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/ActionsRequired.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/ModifiedByExclusionMixIn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/OptionalModifiedByExclusionMixIn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/Profile.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/SupportAccepted.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/SupportDeclined.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/WorkExperience.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/WorkImpacts.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/data/sarprofile/WorkInterests.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceControllerTest.kt
src/test/resources/CreateProfileAcceptedHistories.json
src/test/resources/CreateProfileDeclinedHistories.json

1) Exclude data fields as per SAR guidelines
2) Separate objectMapper for SAR (for field exclusions by Jackson MixIn, isolate from normal use cases)
3) Replicate a set of data classes for SAR DTO:  i) removal of required non-null fields (modifiedBy at some classes) ii) Align with Open API (Swagger) spec. of SAR

[ESWE-1088] SAR data exclusions

---

helm_deploy/hmpps-education-employment-api/values.yaml

- extract connecting string to secrets
- revise actual string at the externalised secrets

[ESWE-1223] Fix appinsights errors

---

build.gradle.kts

- upgrade gradle-spring-boot plugin (`7.1.3`, with Spring Boot to `3.4.3`)
- upgrade `swagger-ui` to `5.20.0`
- upgrade HMMPS SQS lib to `5.3.2`
- upgrade `springdoc-openapi-starter-webmvc-ui` to `2.8.5`

[ESWE-1258] Upgrade dependencies

---

build.gradle.kts

- upgrade gradle-spring-boot plugin (`8.0.0`, with Spring Boot to `3.4.4`)
- upgrade SQS lib to `5.4.2`
- update Kotlin to `2.1.20`

[ESWE-1268] Update dependencies

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/audit/infrastructure/UserPrincipalAuditorAwareShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/config/TestJpaConfig.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/ReadinessProfileIntTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/ReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/shared/application/ApplicationTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/shared/infrastructure/RepositoryTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ProfileObjects.kt
src/integrationTest/resources/application-repository-test.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/repository/ReadinessProfileRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/TestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/service/ProfileServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/shared/application/UnitTestBase.kt

integration tests (repository, etc.), refactor unit tests

[ESWE-1270] revise/add tests

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/ReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/NotesGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ProfileSearchPostShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ProfileStatusChangePutShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ReadinessProfileGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ReadinessProfilePostShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ReadinessProfilePutShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ReadinessProfileV2TestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ProfileObjects.kt
src/integrationTest/resources/jsonprofile/sample2.json
src/integrationTest/resources/jsonprofile/sampleReadinessprofile.json
src/integrationTest/resources/jsonprofile/sampleprofile.json
src/integrationTest/resources/logback-spring.xml
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/config/OpenApiConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/profiledata/domain/CurrentSupportState.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/ProfileNotesResourceController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/SARResourceController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/v1/ProfileResourceControllerV1.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/v2/ProfileResourceController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/ProfileNotesResourceControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/v1/ProfileResourceControllerV1Test.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/v2/ProfileResourceControllerTest.kt

- extract ProfileNotesResourceController
- add more tests around API endpoints
- add basic tests for status change
- clean up unused file
- revise logging levels (of integration tests)
- block change status API at v1 (return `410`)

[ESWE-1271] Profile version `2.0`; refactor controllers, add/revise tests, revise API docs

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

* Spring Boot to `3.4.5` (was `3.4.4`)
* DPS SB plugin to `8.1.0` (was `8.0.0`)
* SQS lib to `5.4.4` (was `5.4.2`)
* Gradle `8.14` (was `8.12.1`)

[ESWE-1306] Upgrade dependencies

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/SARReadinessProfileTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/DashboardMetricsTestCases.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/DashboardTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/MetricsReasonsSupportDeclinedGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v1/ReadinessProfileV1TestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ReadinessProfileV2TestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/shared/application/ApplicationTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/shared/infrastructure/MetricsCountForTest.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/shared/infrastructure/RepositoryTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/shared/infrastructure/TestClock.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ProfileObjects.kt
src/integrationTest/resources/jsonprofile/CreateProfile_correct.json
src/integrationTest/resources/jsonprofile/profileOfStateSupportDeclined.json
src/integrationTest/resources/jsonprofile/sample2.json
src/integrationTest/resources/jsonprofile/sampleprofile.json
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/config/ExceptionAdvice.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ReadinessProfileRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/dashboard/DashboardGet.kt
src/test/resources/jsonprofile/CreateProfile_correct.json

fixes:
* duplicate counts due to wrong joining
* wrong counts whether within or  over 12 weeks
* incorrect API error response
* typos at API function name
fixes at tests
* typos at test data (`within12Weeks`)
integration tests:
* repository tests
* API tests

[ESWE-1153] Metric Reasons for support declined; bug fixes and integration tests

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/DashboardMetricsTestCases.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/MetricsDocumentsSupportNeededGetShould.kt
src/integrationTest/resources/jsonprofile/sample2.json
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/ProfileMetricsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ReadinessProfileRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/dashboard/DashboardGet.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/ProfileMetricsServiceTest.kt

*  native query to collect metric at repository
* API endpoint for metric at `GET` `/dashboard/documents-support-needed`
* relevant unit tests and integration tests

[ESWE-1152] Metric Documents and support needed

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/DashboardMetricsTestCases.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/MetricsWorkStatusGetShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/v2/ReadinessProfileV2TestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ProfileObjects.kt
src/integrationTest/resources/jsonprofile/sample2.json
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/config/OpenApiConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/ProfileMetricsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ReadinessProfileRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/dashboard/DashboardGet.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/ProfileMetricsServiceTest.kt

*  native query to collect metric at repository
* API endpoint for metric at `GET` `/dashboard/work-status`
* relevant unit tests and integration tests
* Revise API spec

[ESWE-1151] Metric Work status progress

---

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryShould.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/readinessprofile/infrastructure/ReadinessProfileRepositoryTestCase.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/DashboardMetricsTestCases.kt
src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/integration/resource/dashboard/MetricsSummaryGetShould.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/MetricsSummaryCount.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/ProfileMetricsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/domain/ReadinessProfileRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/resource/dashboard/DashboardGet.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/educationemployment/api/readinessprofile/application/ProfileMetricsServiceTest.kt

- native query to collect metric at repository
- API endpoint for metric at `GET` `/dashboard/summary`
- relevant unit tests and integration tests
- revise previous metrics' tests

[ESWE-1150] Metric Summary

---

build.gradle.kts

Upgrade:
* Spring Boot plugin `8.3.3` (was `8.3.2`)
* SQS lib `5.4.9` (was `5.4.8`)

[ESWE-1371] Upgrade dependencies
